---
- hosts: all
  become: true
  tasks:
    - import_role:
        name: diskconfig
    - import_role:
        name: geerlingguy.docker
    #    name: atosatto.docker-swarm
    #    name: nickjj.docker
